name: Metrics
on:
  schedule: [{ cron: "0 0 * * *" }]
  workflow_dispatch:
  push: { branches: ["main"] }

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          committer_branch: metrics
          committer_message: "chore: update metrics [skip ci]"

          # --- CONFIGURAÇÃO VISUAL ---
          user: Harlei-Melo
          template: classic
          base: "" # REMOVE TUDO (Header, Activity, etc)
          config_display: large
          config_timezone: America/Sao_Paulo

          # --- O "PULO DO GATO" PARA O RAINBOW ---
          # Removi o 'theme' e o 'gradient()'.
          # Passamos apenas a fila de cores separadas por vírgula.
          # A primeira cor (#161b22) é o "vazio" (fundo dark).
          # As próximas são a intensidade do arco-íris.
          config_colors: "#161b22, #ff0000, #ff7f00, #ffff00, #00ff00, #0000ff, #4b0082, #9400d3"

          # --- PLUGINS ---
          # Gráfico 3D (Isocalendar)
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

          # Streak (Sequência Máxima)
          plugin_streat: yes
          plugin_streat_sections: timeline
